version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paynest-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: paynest
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: somepassword
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: paynest-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paynest
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: somepassword
